FROM selenium/standalone-firefox-debug:3.141.59-titanium

USER root

RUN mkdir -p /authproxy/confdir && \
        chown -R seluser.seluser /authproxy && \
        apt-get update && \
        apt-get install --no-install-recommends -y python3-setuptools python3-pip && \
        rm -f /etc/supervisor/supervisord.conf /etc/supervisord.conf

COPY ./ /authproxy
RUN pip3 --no-cache-dir install -e /authproxy && \
    ln -s /authproxy/supervisor-conf/authproxy.conf \
        /authproxy/supervisor-conf/saml-interceptor.conf \
        /etc/supervisor/conf.d && \
    ln -s /authproxy/supervisor-conf/supervisord.conf /etc

USER seluser


# vim:ft=dockerfile
